server:
  port: 8000
# pgsql 属性配置
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/gateways?currentSchema=public&autoReconnect=true
    username: postgres
    password: 123456
  rabbitmq: #RabbitMQ相关的配置
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest
      listener:
        simple:
          acknowledge-mode: manual
          concurrency: 5
          max-concurrency: 10
      connection-timeout: 15000
  jpa:
    show-sql: true
    hibernate:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
redis:
  host: 192.168.8.150
  port: 6379
  keytimeout: 2000
  timeout: 2000
tcp:
  port: 8090
boss:
  thread:
    count: 2
worker:
  thread:
    count: 2
so:
  keepalive: true
  backlog: 100
websocket:
  path: /websocket
gateway:
  key: 123456