server:
  port: 8081 #服务端口

spring:
  application:
    name: gateway-zuul #指定服务名
zuul:
  routes:
    marscloud-basicinfo-service: #基础数据服务规则
      path: /centre/** #配置请求URL的请求规则
      serviceId: gateway-service-centre
eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:6080/eureka/
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port} #指定实例id
    
management:
  security:
    enabled: false #是否开启actuator安全认证
