server:
  port: 8011 #服务端口
# pgsql 属性配置
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #集团配置
    url: jdbc:postgresql://39.96.84.143:5432/gateways?currentSchema=public&autoReconnect=true
    #本地测试
    #url: jdbc:postgresql://192.168.7.68:5432/gateways?currentSchema=public&autoReconnect=true
    username: postgres
    password: 123456
  rabbitmq: #RabbitMQ相关的配置
      #集团配置
      host: 39.96.84.143
      #本地测试
      #host: 192.168.7.68
      port: 5672
      username: guest
      password: guest
      listener:
        simple:
           acknowledge-mode: manual
           concurrency: 5
           max-concurrency: 10
      connection-timeout: 15000
  jpa:
    show-sql: true
    hibernate:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  kafka:
      bootstrap-servers: 106.120.131.71:9092
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringDeserializer
        value-serializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      consumer:
        group-id: testGrup
        enable-auto-commit: true
        auto-commit-interval: 1000
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
#redis:
 # host: 192.168.8.150
  #port: 6379
  #pool.max-idle: 10
  #pool.min-idle: 10
  #keytimeout: 2000
  #timeout: 2000