# pgsql 属性配置
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.8.150:5432/gateways?currentSchema=public&autoReconnect=true
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    hibernate:
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database: postgresql
  rabbitmq: #RabbitMQ相关的配置
      host: 192.168.8.150
      port: 5672
      username: guest
      password: guest
redis:
  host: 192.168.8.150
  port: 6379
  pool.max-idle: 10
  pool.min-idle: 10
  keytimeout: 2000
  timeout: 2000