server:
  port: 8555 #\u670D\u52A1\u7AEF\u53E3
# pgsql \u5C5E\u6027\u914D\u7F6E
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.8.150:5432/gateways?currentSchema=public&autoReconnect=true
    username: postgres
    password: 123456
  rabbitmq: #RabbitMQ\u76F8\u5173\u7684\u914D\u7F6E
      host: 192.168.8.150
      port: 5672
      username: guest
      password: guest
      listener:
        simple:
           acknowledge-mode: manual
           concurrency: 5
           max-concurrency: 10
      connection-timeout: 15000
  jpa:
    show-sql: true
    hibernate:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
redis:
  host: 192.168.8.150
  port: 6379
  pool.max-idle: 10
  pool.min-idle: 10
  keytimeout: 2000
  timeout: 2000

